apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: integration
spec:
  generators:
    - clusters:
        values:
          sourceRoot: components/integration
          environment: staging
          clusterDir: ""
  template:
    metadata:
      name: integration-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}'
        repoURL: https://github.com/gbenhaim/konflux-ci-infra-deployments
        targetRevision: argo-preview
      destination:
        server: '{{server}}'
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 15s
